
const doctors = [
    {
      name: 'Dr. Ayesha Khan',
      specialization: 'Cardiologist',
      email: 'ayesha.khan@example.com',
      phone: '9876543210',
      qualification: 'MBBS, MD (Cardiology)',
      experience: 10,
      consultationFee: 800,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTime: { start: '10:00 AM', end: '2:00 PM' },
      address: {
        clinicName: 'Heart Care Clinic',
        street: '123 MG Road',
        city: 'Delhi',
        state: 'Delhi',
        pincode: '110001'
      },
      isOnlineConsultant: true,
      profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      rating: 4.5,
      totalRatings: 150
    },
    {
      name: 'Dr. Rohan Mehta',
      specialization: 'Orthopedic Surgeon',
      email: 'rohan.mehta@example.com',
      phone: '9812345670',
      qualification: 'MBBS, MS (Ortho)',
      experience: 12,
      consultationFee: 1000,
      availableDays: ['Tuesday', 'Thursday'],
      availableTime: { start: '11:00 AM', end: '3:00 PM' },
      address: {
        clinicName: 'Bone & Joint Clinic',
        street: '56 Green Park',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400001'
      },
      isOnlineConsultant: false,
      profileImage: 'https://randomuser.me/api/portraits/men/45.jpg',
      rating: 4.8,
      totalRatings: 200
    },
    {
      name: 'Dr. Priya Sharma',
      specialization: 'Dermatologist',
      email: 'priya.sharma@example.com',
      phone: '9876500011',
      qualification: 'MBBS, MD (Dermatology)',
      experience: 8,
      consultationFee: 600,
      availableDays: ['Monday', 'Thursday'],
      availableTime: { start: '10:00 AM', end: '1:00 PM' },
      address: {
        clinicName: 'SkinGlow Clinic',
        street: '87 Sector 15',
        city: 'Noida',
        state: 'UP',
        pincode: '201301'
      },
      isOnlineConsultant: true,
      profileImage: 'https://randomuser.me/api/portraits/women/41.jpg',
      rating: 4.3,
      totalRatings: 120
    },
    {
      name: 'Dr. Arjun Verma',
      specialization: 'General Physician',
      email: 'arjun.verma@example.com',
      phone: '9876500012',
      qualification: 'MBBS',
      experience: 5,
      consultationFee: 500,
      availableDays: ['Tuesday', 'Friday'],
      availableTime: { start: '9:00 AM', end: '12:00 PM' },
      address: {
        clinicName: 'Care Plus Clinic',
        street: '22 Civil Lines',
        city: 'Lucknow',
        state: 'UP',
        pincode: '226001'
      },
      isOnlineConsultant: false,
      profileImage: 'https://randomuser.me/api/portraits/men/46.jpg',
      rating: 4.1,
      totalRatings: 75
    },
    {
      name: 'Dr. Meera Patel',
      specialization: 'Gynecologist',
      email: 'meera.patel@example.com',
      phone: '9876500013',
      qualification: 'MBBS, MS (Gynae)',
      experience: 11,
      consultationFee: 850,
      availableDays: ['Monday', 'Wednesday'],
      availableTime: { start: '11:00 AM', end: '2:00 PM' },
      address: {
        clinicName: 'Women Wellness Center',
        street: 'Plot 7, GIDC',
        city: 'Ahmedabad',
        state: 'Gujarat',
        pincode: '380015'
      },
      isOnlineConsultant: true,
      profileImage: 'https://randomuser.me/api/portraits/women/42.jpg',
      rating: 4.6,
      totalRatings: 130
    },
    {
      name: 'Dr. Nikhil Joshi',
      specialization: 'Neurologist',
      email: 'nikhil.joshi@example.com',
      phone: '9876500014',
      qualification: 'MBBS, DM (Neurology)',
      experience: 15,
      consultationFee: 1200,
      availableDays: ['Tuesday', 'Friday'],
      availableTime: { start: '10:00 AM', end: '1:00 PM' },
      address: {
        clinicName: 'NeuroCare Clinic',
        street: '9 Tilak Nagar',
        city: 'Indore',
        state: 'MP',
        pincode: '452001'
      },
      isOnlineConsultant: false,
      profileImage: 'https://randomuser.me/api/portraits/men/47.jpg',
      rating: 4.9,
      totalRatings: 220
    },
    {
      name: 'Dr. Sana Rizvi',
      specialization: 'ENT Specialist',
      email: 'sana.rizvi@example.com',
      phone: '9876500015',
      qualification: 'MBBS, MS (ENT)',
      experience: 7,
      consultationFee: 700,
      availableDays: ['Monday', 'Thursday'],
      availableTime: { start: '10:00 AM', end: '1:00 PM' },
      address: {
        clinicName: 'Ear Nose Throat Care',
        street: '6 Lalbagh',
        city: 'Bhopal',
        state: 'MP',
        pincode: '462001'
      },
      isOnlineConsultant: true,
      profileImage: 'https://randomuser.me/api/portraits/women/43.jpg',
      rating: 4.4,
      totalRatings: 110
    },
    {
      name: 'Dr. Ramesh Kumar',
      specialization: 'Cardiologist',
      email: 'ramesh.kumar@example.com',
      phone: '9876500016',
      qualification: 'MBBS, MD (Cardiology)',
      experience: 13,
      consultationFee: 950,
      availableDays: ['Wednesday', 'Friday'],
      availableTime: { start: '9:00 AM', end: '1:00 PM' },
      address: {
        clinicName: 'HeartBeat Clinic',
        street: '14 Main Road',
        city: 'Patna',
        state: 'Bihar',
        pincode: '800001'
      },
      isOnlineConsultant: false,
      profileImage: 'https://randomuser.me/api/portraits/men/48.jpg',
      rating: 4.7,
      totalRatings: 180
    },
    {
      name: 'Dr. Anjali Desai',
      specialization: 'Pediatrician',
      email: 'anjali.desai@example.com',
      phone: '9876500017',
      qualification: 'MBBS, MD (Pediatrics)',
      experience: 9,
      consultationFee: 650,
      availableDays: ['Tuesday', 'Thursday'],
      availableTime: { start: '10:30 AM', end: '1:30 PM' },
      address: {
        clinicName: 'Little Steps Clinic',
        street: '4 Andheri West',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400053'
      },
      isOnlineConsultant: true,
      profileImage: 'https://randomuser.me/api/portraits/women/49.jpg',
      rating: 4.2,
      totalRatings: 95
    },
    {
      name: 'Dr. Varun Nair',
      specialization: 'Psychiatrist',
      email: 'varun.nair@example.com',
      phone: '9876500018',
      qualification: 'MBBS, MD (Psychiatry)',
      experience: 6,
      consultationFee: 750,
      availableDays: ['Monday', 'Friday'],
      availableTime: { start: '2:00 PM', end: '6:00 PM' },
      address: {
        clinicName: 'MindCare Clinic',
        street: '89 Residency Road',
        city: 'Bangalore',
        state: 'Karnataka',
        pincode: '560025'
      },
      isOnlineConsultant: true,
      profileImage: 'https://randomuser.me/api/portraits/men/49.jpg',
      rating: 4.5,
      totalRatings: 140
    },
    {
        name: 'Dr. Sneha Kapoor',
        specialization: 'Dermatologist',
        email: 'sneha.kapoor@example.com',
        phone: '9876500019',
        qualification: 'MBBS, MD (Skin)',
        experience: 9,
        consultationFee: 700,
        availableDays: ['Tuesday', 'Friday'],
        availableTime: { start: '11:00 AM', end: '3:00 PM' },
        address: {
          clinicName: 'Skin Aura Clinic',
          street: '12 Park Street',
          city: 'Kolkata',
          state: 'West Bengal',
          pincode: '700016'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/women/50.jpg',
        rating: 4.4,
        totalRatings: 88
      },
      {
        name: 'Dr. Aditya Rana',
        specialization: 'ENT Specialist',
        email: 'aditya.rana@example.com',
        phone: '9876500020',
        qualification: 'MBBS, MS (ENT)',
        experience: 10,
        consultationFee: 780,
        availableDays: ['Wednesday', 'Saturday'],
        availableTime: { start: '10:00 AM', end: '2:00 PM' },
        address: {
          clinicName: 'Rana ENT Clinic',
          street: '33 Sector 9',
          city: 'Chandigarh',
          state: 'Punjab',
          pincode: '160009'
        },
        isOnlineConsultant: false,
        profileImage: 'https://randomuser.me/api/portraits/men/50.jpg',
        rating: 4.6,
        totalRatings: 160
      },
      {
        name: 'Dr. Neha Sood',
        specialization: 'General Physician',
        email: 'neha.sood@example.com',
        phone: '9876500021',
        qualification: 'MBBS',
        experience: 4,
        consultationFee: 500,
        availableDays: ['Monday', 'Thursday'],
        availableTime: { start: '9:00 AM', end: '1:00 PM' },
        address: {
          clinicName: 'Sood Clinic',
          street: '15 Model Town',
          city: 'Ludhiana',
          state: 'Punjab',
          pincode: '141002'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/women/51.jpg',
        rating: 4.1,
        totalRatings: 70
      },
      {
        name: 'Dr. Kabir Malhotra',
        specialization: 'Cardiologist',
        email: 'kabir.malhotra@example.com',
        phone: '9876500022',
        qualification: 'MBBS, MD (Cardiology)',
        experience: 16,
        consultationFee: 1200,
        availableDays: ['Tuesday', 'Friday'],
        availableTime: { start: '10:00 AM', end: '2:00 PM' },
        address: {
          clinicName: 'Pulse Care Hospital',
          street: '92 Marina Street',
          city: 'Chennai',
          state: 'Tamil Nadu',
          pincode: '600004'
        },
        isOnlineConsultant: false,
        profileImage: 'https://randomuser.me/api/portraits/men/51.jpg',
        rating: 4.9,
        totalRatings: 240
      },
      {
        name: 'Dr. Tara Singh',
        specialization: 'Gynecologist',
        email: 'tara.singh@example.com',
        phone: '9876500023',
        qualification: 'MBBS, MS (Gynae)',
        experience: 12,
        consultationFee: 900,
        availableDays: ['Monday', 'Wednesday'],
        availableTime: { start: '10:00 AM', end: '1:00 PM' },
        address: {
          clinicName: 'MotherCare Clinic',
          street: '22 HSR Layout',
          city: 'Bangalore',
          state: 'Karnataka',
          pincode: '560102'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/women/52.jpg',
        rating: 4.7,
        totalRatings: 195
      },
      {
        name: 'Dr. Karan Oberoi',
        specialization: 'Orthopedic Surgeon',
        email: 'karan.oberoi@example.com',
        phone: '9876500024',
        qualification: 'MBBS, MS (Ortho)',
        experience: 14,
        consultationFee: 950,
        availableDays: ['Tuesday', 'Thursday'],
        availableTime: { start: '11:00 AM', end: '2:00 PM' },
        address: {
          clinicName: 'Ortho Plus Clinic',
          street: '11 Saket Nagar',
          city: 'Kanpur',
          state: 'UP',
          pincode: '208014'
        },
        isOnlineConsultant: false,
        profileImage: 'https://randomuser.me/api/portraits/men/52.jpg',
        rating: 4.5,
        totalRatings: 170
      },
      {
        name: 'Dr. Isha Kaul',
        specialization: 'Neurologist',
        email: 'isha.kaul@example.com',
        phone: '9876500025',
        qualification: 'MBBS, DM (Neurology)',
        experience: 10,
        consultationFee: 1100,
        availableDays: ['Wednesday', 'Saturday'],
        availableTime: { start: '10:00 AM', end: '1:00 PM' },
        address: {
          clinicName: 'Neuro Health Hub',
          street: '77 Connaught Place',
          city: 'Delhi',
          state: 'Delhi',
          pincode: '110001'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/women/53.jpg',
        rating: 4.8,
        totalRatings: 210
      },
      {
        name: 'Dr. Rajeev Thakur',
        specialization: 'Psychiatrist',
        email: 'rajeev.thakur@example.com',
        phone: '9876500026',
        qualification: 'MBBS, MD (Psychiatry)',
        experience: 7,
        consultationFee: 780,
        availableDays: ['Monday', 'Thursday'],
        availableTime: { start: '2:00 PM', end: '6:00 PM' },
        address: {
          clinicName: 'Mind Harmony Clinic',
          street: '51 MG Marg',
          city: 'Dehradun',
          state: 'Uttarakhand',
          pincode: '248001'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/men/53.jpg',
        rating: 4.3,
        totalRatings: 130
      },
      {
        name: 'Dr. Alia Bhargav',
        specialization: 'Pediatrician',
        email: 'alia.bhargav@example.com',
        phone: '9876500027',
        qualification: 'MBBS, MD (Pediatrics)',
        experience: 6,
        consultationFee: 680,
        availableDays: ['Tuesday', 'Friday'],
        availableTime: { start: '11:00 AM', end: '2:00 PM' },
        address: {
          clinicName: 'Happy Kids Clinic',
          street: '23 Lal Kuan',
          city: 'Agra',
          state: 'UP',
          pincode: '282001'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/women/54.jpg',
        rating: 4.2,
        totalRatings: 115
      },
      {
        name: 'Dr. Manish Dubey',
        specialization: 'General Physician',
        email: 'manish.dubey@example.com',
        phone: '9876500028',
        qualification: 'MBBS',
        experience: 5,
        consultationFee: 550,
        availableDays: ['Monday', 'Thursday'],
        availableTime: { start: '9:30 AM', end: '12:30 PM' },
        address: {
          clinicName: 'Dubey Clinic',
          street: '67 Jawahar Nagar',
          city: 'Jaipur',
          state: 'Rajasthan',
          pincode: '302004'
        },
        isOnlineConsultant: true,
        profileImage: 'https://randomuser.me/api/portraits/men/54.jpg',
        rating: 4.0,
        totalRatings: 90
      }
    ];

    module.exports = { data: doctors };
